Added CustomGlobalExceptionHandler and enhance DTO validation
ShastkivRuslan/online-book-shop pull request #5
Opened 2024-10-16 05:07 UTC by ShastkivRuslan

Added CustomGlobalExceptionHandler for centralized exception handling and enhance DTO validation

- Implemented CustomGlobalExceptionHandler to manage application-wide exceptions and improve error responses
- Added @CoverImage annotation to validate URL format for book cover images
- Added @Isbn annotation to validate ISBN format for book ISBNs in CreateBookRequestDto

2024-10-16 12:50 UTC, Elena-Bruyako requested changes
see comments

2024-10-16 12:50 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/controller/BookController.java
> +    public BookDto createBook(@Valid @RequestBody CreateBookRequestDto bookDto) {
Do we need `@Valid` for other endpoints?

2024-10-16 12:50 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/dto/CreateBookRequestDto.java
> +    @NotNull(message = "Title cannot be null")
use `@NotBlank` for String

```suggestion
    @NotBlank(message = "Title cannot be null")
```

2024-10-17 09:16 UTC, okuzan approved these changes

2024-10-18 03:08 UTC, merged