Add User Registration Functionality
ShastkivRuslan/online-book-shop pull request #7
Opened 2024-10-30 14:24 UTC by ShastkivRuslan

This pull request introduces user registration functionality into the system, including the new User entity, corresponding DTOs, an authentication controller, and an error handling mechanism. Key changes include:

Addition of User Entity:

Fields:

- id (Long, PK)
- email (String, not null, unique)
- password (String, not null)
- firstName (String, not null)
- lastName (String, not null)
- shippingAddress (String)

Creation of DTO Classes:

-UserRegistrationRequestDto: for receiving data about the new user during registration.
-UserResponseDto: for returning information about the registered user.
Addition of Mapper:

-Utilizing MapStruct for transforming between the User entity and the corresponding DTOs.
AuthenticationController:

-Added method register(UserRegistrationRequestDto request) throws RegistrationException, which handles user registration requests.
Data Validation:

-Implementing validation annotations in the new DTO classes to ensure the correctness of incoming data.
-Added the @PasswordMatcher annotation to check that the password and repeatPassword fields in UserRegistrationRequestDto are the same.
Error Handling:

-Implemented error handling for registration using GlobalExceptionHandler for centralized management of exceptions that may occur during registration.

2024-10-30 14:46 UTC, Elena-Bruyako requested changes
see comments

2024-10-30 14:46 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/exception/GlobalExceptionHandler.java
> +        return new ResponseEntity<>(errorResponse, HttpStatus.BAD_REQUEST);
```suggestion
        return new ResponseEntity<>(errorResponse, HttpStatus.CONFLICT);
```

2024-10-30 14:46 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/service/user/UserServiceImpl.java
> +        if (userRepository.findByEmail(registrationRequestDto.email()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(registrationRequestDto.email())) {
```

2024-10-30 14:46 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/service/user/UserServiceImpl.java
> +        return userMapper.toDto(
don't call several methods inline, use local variables

2024-10-31 08:09 UTC, liliia-ponomarenko approved these changes
Good job! But please fix my comments before merging ;)

2024-10-31 08:09 UTC, liliia-ponomarenko commented on src/main/java/ruslan/shastkiv/bookstore/exception/GlobalExceptionHandler.java
> +
```suggestion
```

2024-10-31 08:09 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(50)
Better use the same length validators with dto. Otherwise, you may get an exception when saving to the DB.

2024-10-31 08:09 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
the same

2024-10-31 08:09 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
leave one empty line at the end of the file (check other files)

2024-11-04 04:59 UTC, merged