Security second part
ShastkivRuslan/online-book-shop pull request #8
Opened 2024-11-05 05:33 UTC by ShastkivRuslan

Add Spring Security configuration and Role-based access control

- Integrate spring-boot-starter-security and create SecurityConfig with PasswordEncoder and SecurityFilterChain beans
- Implement UserDetails interface in User entity and create UserDetailsService implementation
- Make /api/auth/register endpoint public and restrict other endpoints based on user roles
- Create Role entity, RoleRepository, and establish Many-to-Many relationship between User and Role entities
- Add changeset to create roles in the database and assign roles to users
- Configure Swagger to remain accessible
- Update User entity to include roles, and use `@PreAuthorize` for role-based access control on endpoints

2024-11-05 08:17 UTC, Elena-Bruyako requested changes
see comments

2024-11-05 08:17 UTC, Elena-Bruyako commented on pom.xml
> +            <version>3.3.5</version>
```suggestion
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/controller/BookController.java
>      public BookDto updateBook(@PathVariable Long id, @RequestBody CreateBookRequestDto requestDto) {
```suggestion
    public BookDto updateBook(@PathVariable Long id, @RequestBody @Valid CreateBookRequestDto requestDto) {
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/controller/BookController.java
> +    public List<BookDto> search(BookSearchParametersDto searchParametersDto, Pageable pageable) {
check other Pageable
```suggestion
    public List<BookDto> search(BookSearchParametersDto searchParametersDto, @ParameterObject @PageableDefault Pageable pageable) {
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/model/Role.java
> +@Entity
```suggestion
@Entity
@Getter
@Setter
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/model/User.java
> +    private Set<Role> roles;
```suggestion
    private Set<Role> roles = new HashSet<>();
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/repository/user/UserRepository.java
> +    Optional<User> findUserWithRolesByEmail(@Param("email") String email);
```suggestion
    @EntityGraph(attributePaths = "roles")
    Optional<User> findByEmail(String email);
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/security/UserDetailsServiceImpl.java
> +        return userRepository.findUserWithRolesByEmail(email).orElseThrow(
```suggestion
        return userRepository.findByEmail(email).orElseThrow(
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/security/UserDetailsServiceImpl.java
> +                () -> new UsernameNotFoundException("Can`t find user by email ["
```suggestion
                () -> new EntityNotFoundException("Can`t find user by email ["
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/service/user/UserServiceImpl.java
> +        User savedUser = userRepository.save(userFromRequest);
set USER role to user

```suggestion
        User user = userMapper.toModel(registrationRequestDto);
        user.setPassword(passwordEncoder.encode(registrationRequestDto.password()));
        userRepository.save(user);
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/java/ruslan/shastkiv/bookstore/service/user/UserServiceImpl.java
>          return userMapper.toDto(savedUser);
```suggestion
        return userMapper.toDto(user);
```

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
add isDeleted column

2024-11-05 08:17 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/06-add-is_deleted-column.yaml
> +      id: add-is_deleted-column
remove

2024-11-06 07:27 UTC, liliia-ponomarenko approved these changes
Great 🔥 A few recommendations ;)

2024-11-06 07:27 UTC, liliia-ponomarenko commented on src/main/java/ruslan/shastkiv/bookstore/controller/BookController.java
> +    public List<BookDto> getAll(@ParameterObject @PageableDefault Pageable pageable) {
Better return Page instead List

2024-11-06 07:27 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                    nullable: false
Better create a new changeSet. On a real project, you would get a checksum mismatch error

2024-11-09 18:22 UTC, merged